substitutions:
  name: satellite1
  friendly_name: Satellite1
  xmos_fw_version: "v1.0.3"
  log_level: debug

esphome:
  name: ${name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}

packages:
  Charlene.Satellite1:
    url: "https://github.com/D8EDB/charlene-wake-word"
    ref: "main"
    refresh: 1s
    files:
      - config/satellite1.base.yaml
      - config/common/dashboard_build.yaml
      - path: config/common/components.external.yaml
        vars:
          ext_comp_repo_url: "https://github.com/FutureProofHomes/Satellite1-ESPHome"
          ext_comp_repo_ref: "473d7b7d0870c402c32fd358d411420f90ab1d87"

logger:
  level: ${log_level}
